version: '3.1'

services:

  mysql:
    image: mysql:8.0.17
    restart: always
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: q1w2E!R
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - 18361:3306
    volumes:
      - ./data/mysql:/var/lib/mysql

networks:
  default:
    external:
      name: airflow 